apiVersion: v1
kind: Secret
metadata:
  name: mosip-ida-secrets
  namespace: mosip-ida
type: Opaque
data:
  # Database password (base64 encoded)
  # Note: In production, use proper secret management
  DB_PASSWORD: cG9zdGdyZXM= # "postgres" in base64
