# MOSIP ID Authentication CI/CD Configuration
# This file contains shared configuration for all workflows

# Default environment variables
defaults:
  java_version: "11"
  maven_version: "3.8.7"
  aws_region: "us-east-1"
  docker_registry: "mosip"

# Service configurations
services:
  authentication-service:
    name: "authentication-service"
    port: 8090
    health_port: 9010
    path: "authentication/authentication-service"
    description: "Main authentication service"

  authentication-internal-service:
    name: "authentication-internal-service"
    port: 8093
    health_port: 9010
    path: "authentication/authentication-internal-service"
    description: "Internal authentication service"

  authentication-otp-service:
    name: "authentication-otp-service"
    port: 8092
    health_port: 9010
    path: "authentication/authentication-otp-service"
    description: "OTP authentication service"

# Build configurations
build:
  maven:
    skip_tests: false
    parallel: true
    threads: 2

  docker:
    build_args:
      spring_config_label: "${VERSION}"
      active_profile: "${ENVIRONMENT}"
      spring_config_url: "${SPRING_CONFIG_URL}"
      artifactory_url: "${ARTIFACTORY_URL}"
      biosdk_zip_path: "${BIOSDK_ZIP_PATH}"
      demosdk_zip_path: "${DEMOSDK_ZIP_PATH}"
      hsm_client_zip_path: "${HSM_CLIENT_ZIP_PATH}"
      iam_adapter_url: "${IAM_ADAPTER_URL}"
      is_glowroot: "${IS_GLOWROOT}"

# Security configurations
security:
  trivy:
    enabled: true
    severity: "HIGH,CRITICAL"
    format: "sarif"

  image_scanning:
    enabled: true
    scan_on_push: false

# Cleanup configurations
cleanup:
  retention_days: 30
  dry_run: true
  schedule: "0 2 * * 0" # Every Sunday at 2 AM UTC

  repositories:
    - "mosip-authentication-service"
    - "mosip-authentication-internal-service"
    - "mosip-authentication-otp-service"

# Notification configurations
notifications:
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"

  github:
    enabled: true
    summary: true
    comments: true

# Environment configurations
environments:
  dev:
    active_profile: "dev"
    spring_config_url: "http://config-server:8888"
    artifactory_url: "http://artifactory:8081"

  staging:
    active_profile: "staging"
    spring_config_url: "http://config-server-staging:8888"
    artifactory_url: "http://artifactory-staging:8081"

  prod:
    active_profile: "prod"
    spring_config_url: "http://config-server-prod:8888"
    artifactory_url: "http://artifactory-prod:8081"

# Workflow triggers
triggers:
  push:
    branches:
      - "main"
      - "master"
      - "develop"
      - "release/*"
      - "feature/*"
    paths:
      - "authentication/**"
      - ".github/workflows/**"

  pull_request:
    branches:
      - "main"
      - "master"
      - "develop"
    paths:
      - "authentication/**"
      - ".github/workflows/**"

  schedule:
    - "0 2 * * 0" # Weekly cleanup

  workflow_dispatch:
    inputs:
      environment:
        type: "choice"
        options: ["dev", "staging", "prod"]
        default: "dev"
      version:
        type: "string"
        default: ""
      skip_tests:
        type: "boolean"
        default: false
      dry_run:
        type: "boolean"
        default: true
